version: '>= 0.13.0, < 1.0.0'
formatter: markdown table
recursive:
  enabled: true
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
sort:
  enabled: true
  by: name
settings:
  indent: 4
  escape: false
  default: false
  required: true
  type: true
  hide-empty: true
  read-comments: true
  color: true
Transform: AWS::Serverless-2016-10-31
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties: {}
  Service:
    Type: AWS::ECS::Service
    Properties: {}
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: {}
  Repository:
    Type: AWS::ECR::Repository
    Properties: {}
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: Group
      Members:
        - Cluster
        - Service
        - TaskDefinition